name: 'Commit message matcher'
description: 'Check whether last commint message matches a given pattern'
inputs:
  pattern:
    description: 'pattern to match'
    required: true
outputs:
  matches:
    description: "Whether message matchers a pattern (a string true or false)"
    value: ${{ steps.commit-message-matcher.outputs.matches }}
runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash

    - id: commit-message-matcher
      run: |
        SHA=${{ github.event.after }}
        ${{ github.action_path }}/matcher.sh "$SHA" "${{ inputs.pattern }}"
      shell: bash
