name: 'Commit message matcher'
description: 'Check whether last commint message matches a given pattern'
inputs:
  pattern:
    description: 'pattern to match'
    required: true
outputs:
  matches:
    description: "Whether message matchers a pattern (a string true or false)"
    value: ${{ steps.commit-message-matcher.outputs.matches }}
runs:
  using: "composite"
  steps:
    - id: commit-message-matcher
      run: |
        if [[ ! -z "${{ github.event.after }}" ]]; then
          SHA="${{ github.event.after }}"
        else
          SHA="${{ github.sha }}"
        fi
        ${{ github.action_path }}/matcher.sh "$SHA" "${{ inputs.pattern }}"
      shell: bash
